export enum Role {
  STUDENT = 'STUDENT',
  PROVIDER = 'PROVIDER',
  ADMIN = 'ADMIN'
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_VERIFICATION = 'UNDER_VERIFICATION',
  DOCUMENT_DEFICIENCY = 'DOCUMENT_DEFICIENCY',
  CORRECTION_REQUIRED = 'CORRECTION_REQUIRED',
  VERIFIED = 'VERIFIED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISBURSEMENT_PENDING = 'DISBURSEMENT_PENDING',
  DISBURSED = 'DISBURSED'
}
